version: '3.5'
networks:
  web:
    external: true
  elastic: 
    driver: bridge
volumes:
  dbdata6:
  elasticsearch-data:
services:
  mongo-db: 
    image: mongodb/mongodb-community-server:5.0-ubi8 
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - 'dbdata6:/data/db'
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    ports:
      - 9200:9200
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    networks:
      - elastic
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.7.1
    ports:
      - '5601:5601'
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - elastic
  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-CU18-ubuntu-20.04
    environment:
      - "/etc/timezone:/etc/timezone:ro" 
      - "/etc/localtime:/etc/localtime:ro"
      - ACCEPT_EULA=Y
      - MSSQL_PID=EXPRESS
      - SA_PASSWORD=z@123456!
    ports:
      - target: 1433
        published: 1434
  redis: 
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
  public-transportation-pickup-api:
    container_name: public-transportation-pickup-api
    tty: true
    volumes:
    - "/etc/localtime:/etc/localtime:ro"
    depends_on:
      - sql-server
      - redis
    image: ${DOCKER_REGISTRY-}public-transportation-pickup-api:v1
    build: 
      context: .
      dockerfile: APIs/PTP.WebAPI/Dockerfile
    environment:
    - "/etc/timezone:/etc/timezone:ro" 
    - "/etc/localtime:/etc/localtime:ro"
    - CONNECTIONSTRINGS__DEFAULTCONNECTION=Server=sql-server;Database=[PTP.Database];Trusted_Connection=False;User Id=sa;Password=z@123456!;MultipleActiveResultSets=true;TrustServerCertificate=true
    - ConnectionStrings__RedisConnection=redis:6379
    - CONNECTIONSTRINGS__MONGODBCONNECTION=mongodb://mongo-db:27017
    ports:
    - "5000:80"



