version: '3.5'
networks:
volumes:
  dbdata6:
  elasticsearch-data:
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "4317:4317"
      - "4318:4318"
      - "16686:16686"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
  seq:
    image: datalust/seq
    ports:
      - "80:80"
      - "5341:5341"
    environment:
      - ACCEPT_EULA=Y
  mongo-db: 
    image: mongodb/mongodb-community-server:5.0-ubi8 
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
    environment: 
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-CU18-ubuntu-20.04
    environment:
      - "/etc/timezone:/etc/timezone:ro" 
      - "/etc/localtime:/etc/localtime:ro"
      - ACCEPT_EULA=Y
      - MSSQL_PID=EXPRESS
      - SA_PASSWORD=z@123456!
    ports:
      - target: 1433
        published: 1434
  redis: 
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
  public-transportation-pickup-api:
    container_name: public-transportation-pickup-api
    tty: true
    volumes:
    - "/etc/localtime:/etc/localtime:ro"
    depends_on:
      - sql-server
      - redis
    image: ${DOCKER_REGISTRY-}public-transportation-pickup-api:v1
    build: 
      context: .
      dockerfile: APIs/PTP.WebAPI/Dockerfile
    environment:
    - "/etc/timezone:/etc/timezone:ro" 
    - "/etc/localtime:/etc/localtime:ro"
    - CONNECTIONSTRINGS__DEFAULTCONNECTION=Server=sql-server;Database=[PTP.Database];Trusted_Connection=False;User Id=sa;Password=z@123456!;MultipleActiveResultSets=true;TrustServerCertificate=true
    - ConnectionStrings__RedisConnection=redis:6379
    - CONNECTIONSTRINGS__MONGODBCONNECTION=mongodb://admin:adminpassword@mongo-db:27017/?authSource=admin
    ports:
    - "5000:80"



